databases:
  - name: mysurveydb
    plan: free
    databaseName: mysurvey
    user: mysurvey_project

services:
  - type: web
    plan: free
    name: mysurvey_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysurvey_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysurveydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4